### ISSUE TITLE
Formatting Options?

### ISSUE THREAD

**Issue by InputandOutput** [BasicallyIAmFox/ExpandedTooltips#2]
Hello, I was wondering if Expanded Tooltips supports a custom formatting scheme or a standard formatting scheme (i.e. colors, italics, bold, strikethrough) to description text. Let me know if this is the case or not.

**Comment by BasicallyIAmFox** [comment]
no (you'd have to edit source and re-compile the mod)

**Comment by InputandOutput** [comment]
Dang. Are there any plans to implement such a feature? If not, then this issue can be closed.

**Comment by BasicallyIAmFox** [comment]
i believe you could say mod is basically dead; not sure what others are up to nor if they're active

**Comment by InputandOutput** [comment]
I understand. Closing this issue.
